export const RoutesString = {
  home: "/",
  search: "/search",
  profile: "/profile",
  otherProfile: "/profile/:id",
  createTrip: "/createTrip",
  register: "/register",
  login: "/login",
  chat: "/chat",
  landing: "/landing",
  infouser: "/infouser",
  editUser: "/editUser",
  motorbike: "/motorbike",
  settings: "/settings",
  editPassword: "/editPassword",
  route: "/route",
  routeDetail: "/route/:id",
};
