export const RoutesString = {
  home: "/",
  profile: "/profile",
  otherProfile: "/profile/:id",
  register: "/register",
  login: "/login",
  chat: "/chat",
  chatDetail: "/chat/:id",
  chatbot: "/chatbot",
  landing: "/landing",
  infouser: "/infouser",
  editUser: "/editUser",
  motorbike: "/motorbike",
  settings: "/settings",
  editPassword: "/editPassword",
  route: "/route",
  routeDetail: "/route/:id",
  theme: "/theme",
  language: "/language",
};
